### ISSUE TITLE
How can i update lms

### ISSUE THREAD

**Issue by justinw78** [jboesl/docker-logitechmediaserver#3]
Hello:)

if i do sudo dpkg -i /config/cache/updates/logitechmediaserver_7.9.2~1564788734_amd64.deb then sudo isn't working en with su i must be in a termial.

Hope you know the anwere:)

greetings

**Comment by jboesl** [comment]
I'm not sure I understand what your question is. With docker you just pull a new image and start a fresh container from it. You are not supposed to run updates in the container.
