### ISSUE TITLE
user and group configuration seems not to work

### ISSUE THREAD

**Issue by slenarduzzi** [jboesl/docker-logitechmediaserver#5]
I get the following error when I add PUID and GUID in the configuration of the container on Synology's Docker :

![image](https://user-images.githubusercontent.com/77481068/104695902-bce13800-570d-11eb-88e8-57ff2e76ad53.png)

![image](https://user-images.githubusercontent.com/77481068/104696014-e13d1480-570d-11eb-8949-dadc8a2f0b59.png)

If I log in into the bash shell, the ID command shows 101 instead of 1027 :
```
  squeezeboxserver@logitechmediaserver1:/$ id                                        
  uid=101(squeezeboxserver) gid=65534(nogroup) groups=65534(nogroup)

```
Thanks

**Comment by texneus** [comment]
Same problem here.  PUID and GUID are just ignored.  I thought I read somewhere a few years back that the environment variables for user/group IDs in Docker were depreciated...but don't quote me on that.  Using the -u or --user parameter on the docker statement does work as advertized...the container now operates under the ID and group I specify.  The config and music directories naturally must have compatible permissions.

Docker command line that works:
```
docker create \
--name logitechmediaserver \
--net host \
--restart=on-failure:5 \
-u 1000:100 \
-v /path/to/config:/config \
-v /path/to/music:/mnt/Music:ro \
-v /etc/localtime:/etc/localtime:ro \
-t -i jboesl/logitechmediaserver
```

**Comment by jboesl** [comment]
I'm no longer changing anything here besides doing basic updates. I think you should take a look at the official image which recently emerged: https://hub.docker.com/r/lmscommunity/logitechmediaserver
